[project]
name = "thinkback"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.142.2",
    "fastembed>=0.8.1",
    "groq>=1.7.0",
    "pydantic>=2.13.5",
    "python-dotenv>=1.2.4",
    "qdrant-client>=1.19.1",
    "torch==2.8.0",
    "uvicorn>=0.54.0",
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
